# Generated by Django 4.2.5 on 2023-09-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_choice_questioncategory_questionset_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncategory',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='questionset',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
